Update 8. CreatingDockerfileForGitRepo.md

diff --git a/8. CreatingDockerfileForGitRepo.md b/8. CreatingDockerfileForGitRepo.md
--- a/8. CreatingDockerfileForGitRepo.md
+++ b/8. CreatingDockerfileForGitRepo.md
@@ -63,4 +63,37 @@ understood then there should be no problem replicating the same for other apps t
     
    ```
    CMD ["npm", "run", "dev"]
-   ```  
+   ```
+
+So the whole file will look like this
+   ````
+   FROM node:20-alpine
+   
+   # Set the working directory inside the container
+   WORKDIR /mplus
+   
+   # Install Git
+   RUN apk add --no-cache git
+   
+   # Clone the Git repository into the container
+   RUN git clone https://github.com/AniJadeja/luxe-wheels-backend.git
+   
+   #Change the work dir to the repo
+   WORKDIR /mplus/luxe-wheels-backend
+   
+   # Verify that the repository contains a package.json file
+   RUN test -f package.json || { echo "Error: package.json not found in repository"; exit 1; }
+   
+   # Install dependencies
+   RUN npm install
+   
+   # Expose port 10000
+   EXPOSE 10000
+   
+   # Copy the required files
+   COPY .env .
+   COPY serviceAccountKey.json .
+   
+   # Start the application
+   CMD ["npm", "run", "dev"]
+   ```
